- create:
    - ~/.local/src
    - ~/.local/bin
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install dependencies
      command: |
        if [ `uname` = 'Linux' ]; then
          case $(lsb_release -is) in 
            Ubuntu)
            ;;
            Arch | EndeavourOS)
              sudo pacman -S --noconfirm \
                cmake \
                freetype2 \
                fontconfig \
                pkg-config \
                make \
                libxcb \
                libxkbcommon \
                python
            ;;
          esac
        fi
    - description: Installing Alacritty
      command: |

        if [ ! -f /usr/local/bin/alacritty ]; then
        #Install alacritty
         [ -d $HOME/.local/src/alacritty ] || git clone https://github.com/alacritty/alacritty.git $HOME/.local/src/alacritty
          
          cd $HOME/.local/src/alacritty
          $HOME/.cargo/bin/rustup override set stable
          $HOME/.cargo/bin/rustup update stable

          if [ `uname` = 'Linux' ]; then
            $HOME/.cargo/bin/cargo build --release

            ### Force support for only Wayland ###
            #cargo build --release --no-default-features --features=wayland

            ### Force support for only X11 ###
            #cargo build --release --no-default-features --features=x11
          elif [ `uname` = 'Darwin' ]; then
            sudo xcodebuild -license accept
            make app
            cp -r target/release/osx/Alacritty.app /Applications/
          fi

          sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
          infocmp alacritty

          if [ `uname` = 'Linux' ]; then
            # Desktop Icon
            sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
            sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
            sudo desktop-file-install extra/linux/Alacritty.desktop
            sudo update-desktop-database
          fi


          #Install man page
          sudo mkdir -p /usr/local/share/man/man1
          gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
          gzip -c extra/alacritty-msg.man | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null


          mkdir -p $HOME/.local/share/alacritty
          cp alacritty.yml $HOME/.local/share/alacritty/ #copy config default
          #cp extra/completions/_alacritty $HOME/.local/share/alacritty/ #copy completions

          # Default terminal
          if [ `uname` = 'Linux' ]; then
            if [ $(lsb_release -is) = 'Ubuntu' ]; then
              sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 100
              sudo update-alternatives --config x-terminal-emulator
            fi
          fi

          #sudo rm -r $HOME/.local/src/alacritty 
        fi
      stdout: true

- link:
    ~/.config/alacritty: alacritty
    ~/.zshrc.d/019-alacritty.zsh: zshrc.d/019-alacritty.zsh
