- create:
    - ~/.local/src
    - ~/.local/bin
    - ~/.local/share/zsh/site-functions
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Remove previous asdf folder
      command: "[ ! -d ~/.asdf ] || sudo rm -rf ~/.asdf"

    - description: Clone asdf
      command: |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1

    - description: Install asdf packages
      command: |
        export ASDF_DIR="$HOME/.asdf"
        export PATH="$PATH:$HOME/.asdf/bin"
        echo '. "$HOME/.asdf/asdf.sh"' | tee -a ~/.bashrc > /dev/null
        cp $HOME/.asdf/completions/_asdf $HOME/.local/share/zsh/site-functions
        . "$HOME/.asdf/asdf.sh"
        . ~/.bashrc

        if [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              sudo apt-get install -y \
                dirmngr \
                gpg \
                curl \
                gawk \
                coreutils
          esac
        fi

    - description: Install Java
      command: |
        export ASDF_DIR="$HOME/.asdf"
        export PATH="$PATH:$HOME/.asdf/bin"
        . "$HOME/.asdf/asdf.sh"
        asdf plugin add java https://github.com/halcyon/asdf-java.git
        asdf install java latest:adoptopenjdk-17
        asdf install java latest:liberica-17
        asdf global  java latest:adoptopenjdk-17

    - description: Install Kotlin
      command: |
        $HOME/.asdf/bin/asdf plugin add kotlin https://github.com/asdf-community/asdf-kotlin.git
        $HOME/.asdf/bin/asdf install kotlin latest
        $HOME/.asdf/bin/asdf global  kotlin latest

    - description: Install Groovy
      command: |
        $HOME/.asdf/bin/asdf plugin add groovy https://github.com/weibemoura/asdf-groovy.git
        $HOME/.asdf/bin/asdf install groovy latest
        $HOME/.asdf/bin/asdf global  groovy latest

    - description: Install Gradle
      command: |
        $HOME/.asdf/bin/asdf plugin add gradle https://github.com/rfrancis/asdf-gradle.git
        $HOME/.asdf/bin/asdf install gradle 8.2.1
        $HOME/.asdf/bin/asdf global gradle 8.2.1

    - description: Install Maven
      command: |
        $HOME/.asdf/bin/asdf plugin add maven https://github.com/halcyon/asdf-maven.git
        $HOME/.asdf/bin/asdf install maven latest
        $HOME/.asdf/bin/asdf global maven latest

    - description: Install jq
      command: |
        export ASDF_DIR="$HOME/.asdf"
        export PATH="$PATH:$HOME/.asdf/bin"
        . "$HOME/.asdf/asdf.sh"
        asdf plugin add jq https://github.com/lsanwick/asdf-jq.git
        asdf install jq latest
        asdf global jq latest

    - description: Install bun
      command: |
        $HOME/.asdf/bin/asdf plugin add bun https://github.com/cometkim/asdf-bun.git
        $HOME/.asdf/bin/asdf install bun latest
        $HOME/.asdf/bin/asdf global bun latest

    - description: Install Flutter
      command: |
        export ASDF_DIR="$HOME/.asdf"
        export PATH="$PATH:$HOME/.asdf/bin"
        . "$HOME/.asdf/asdf.sh"

        # export PATH="$PATH:$HOME/.asdf/installs/jq/1.7/bin"
        #alias jq=$HOME/.asdf/installs/jq/1.7/bin/jq
        asdf plugin-add flutter
        asdf install flutter 3.10.6-stable
        asdf global flutter 3.10.6-stable

    - description: Install Dart
      command: |
        $HOME/.asdf/bin/asdf plugin add dart https://github.com/patoconnor43/asdf-dart.git
        $HOME/.asdf/bin/asdf install dart latest
        $HOME/.asdf/bin/asdf global dart latest

    - description: Install dotnet-core
      command: |
        $HOME/.asdf/bin/asdf plugin add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
        $HOME/.asdf/bin/asdf install dotnet-core latest
        $HOME/.asdf/bin/asdf global dotnet-core latest

- link:
    ~/.asdfrc: asdf/asdfrc
    ~/.zshrc.d/004-asdf.zsh: zshrc.d/004-asdf.zsh
    ~/.zshrc.d/007-java.zsh: zshrc.d/007-java.zsh
    ~/.zshrc.d/008-flutter.zsh: zshrc.d/008-flutter.zsh

- shell:
  - [ exec $SHELL -l ]
