- shell:
  - description: Clone asdf
    command: 'git clone https://github.com/asdf-vm/asdf.git ~/.asdf'
    stderr: true
- link:
    ~/.asdfrc:
- asdf:
  - plugin: java
    url: https://github.com/halcyon/asdf-java.git
    global: temurin-11.0.12+12
    versions:
      - temurin-17.0.1+12
      - temurin-11.0.12+7
      - adoptopenjdk-8.0.181+13
  - plugin: gradle
    url: https://github.com/rfrancis/asdf-gradle.git
    global: 6.5.1
    versions:
      - 6.5.1
