- shell:
    - description: Remove previous asdf folder
      command: "[ ! -d ~/.asdf ] || sudo rm -rf ~/.asdf "
    - description: Clone asdf
      command: |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
        export PATH="$PATH:$HOME/.asdf/bin"
        echo '. "$HOME/.asdf/asdf.sh"' | tee ~/.bashrc > /dev/null
        . ~/.bashrc
- link:
    ~/.asdfrc: asdf/asdfrc
    ~/.zshrc.d/018-asdf.zsh: zshrc.d/018-asdf.zsh

- shell:
    - [source ~/.bashrc]
- asdf:
    - plugin: direnv
      url: https://github.com/asdf-community/asdf-direnv.git
      shell: zsh
      global: latest
      versions:
        - latest
    - plugin: bun
      url: https://github.com/cometkim/asdf-bun.git
      global: latest
      versions:
        - latest
    - plugin: jq
      url: https://github.com/AZMCode/asdf-jq.git
      global: latest
      versions:
        - latest
    - plugin: argocd
      url: https://github.com/beardix/asdf-argocd.git
      global: latest
      versions:
        - latest
    - plugin: dotnet-core
      url: https://github.com/emersonsoares/asdf-dotnet-core.git
      global: latest
      versions:
        - latest
    - plugin: java
      url: https://github.com/halcyon/asdf-java.git
      global: temurin-19.0.2+7
      versions:
        - temurin-19.0.2+7
        - temurin-8.0.362+9
    - plugin: gradle
      url: https://github.com/rfrancis/asdf-gradle.git
      global: 6.5.1
      versions:
        - 6.5.1
    - plugin: flutter
      url: https://github.com/oae/asdf-flutter.git
      global: 3.3.7-stable
      versions:
        - 3.3.7-stable
    - plugin: dart
      url: https://github.com/patoconnor43/asdf-dart.git
      global: latest
      versions:
        - latest
    - plugin: rust
      url: https://github.com/code-lever/asdf-rust.git
      global: latest
      versions:
        - latest
