- shell:
    - description: Remove previous asdf folder
      command: "[ ! -d ~/.asdf ] || sudo rm -rf ~/.asdf"
    - description: Clone asdf
      command: |
        sudo apt-get install -y git
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
- link:
    ~/.asdfrc: asdf/asdfrc
    ~/.zshrc.d/018-asdf.zsh: zshrc.d/018-asdf.zsh

- shell:
    - description: Install asdf packages
      command: |
        export PATH="$PATH:$HOME/.asdf/bin"
        echo '. "$HOME/.asdf/asdf.sh"' | tee -a ~/.bashrc > /dev/null
        . "$HOME/.asdf/asdf.sh"
        . ~/.bashrc

        sudo apt-get install -y \
          dirmngr \
          gpg \
          curl \
          gawk

    # - description: Install Java
    #   command: |
    #     asdf plugin add java https://github.com/halcyon/asdf-java.git
    #     asdf install java latest

    - description: Install jq
      command: |
        asdf plugin add jq https://github.com/AZMCode/asdf-jq.git
        asdf install jq latest
        asdf global jq latest
      stdout: true

    - description: Install bun
      command: |
        asdf plugin add bun https://github.com/cometkim/asdf-bun.git
        asdf install bun latest
        asdf global bun latest

    - description: Install Flutter
      command: |
        asdf plugin-add flutter
        asdf install flutter 3.7.12-stable
        asdf global flutter 3.7.12-stable
      stdout: true

    - description: Install Dart
      command: |
        asdf plugin add dart https://github.com/patoconnor43/asdf-dart.git
        asdf install dart latest
        asdf global dart latest

    - description: Install dotnet-core
      command: |
        asdf plugin add dotnet-core https://github.com/emersonsoares/asdf-dotnet-core.git
        asdf install dotnet-core latest
        asdf global dotnet-core latest
      stdout: true
