- git:    
    '~/.asdf':
      url: 'https://github.com/asdf-vm/asdf.git'
      description: 'Clone asdf'
- link:
    ~/.asdfrc:
- asdf:
  - plugin: java
    url: https://github.com/halcyon/asdf-java.git
    global: temurin-17.0.1+12
    versions:
      - temurin-17.0.1+12
  - plugin: gradle
    url: https://github.com/rfrancis/asdf-gradle.git
    global: 6.5.1
    versions:
      - 6.5.1