# This apply to all commands that come after setting the defaults.
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install brew
      command: |
        if [ ! -x /usr/local/bin/brew ]; then
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
- defaults:
    brewfile:
      stdout: true
      stderr: true
      include: ["tap", "brew", "cask", "mas"]

- brewfile:
    # This accepts the same options as `brew bundle` command:
    file: brew/Brewfile

- link:
    ~/.config/bat: bat
    ~/.gitconfig: git/gitconfig
    ~/.zshrc.d/003-brew-completions.zsh:
      if: "[ `uname` = Darwin ]"
      path: zshrc.d/003-brew-completions.zsh
