- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description:
      command: "sudo apt-get -y update"
    - description: Installind packages
      command: |
        sudo apt-get install -y \
          make \
          cmake \
          gcc \
          clang \
          wget \
          curl \
          build-essential \
          libssl-dev \
          zlib1g-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          lsb-release \
          ca-certificates \
          apt-transport-https \
          software-properties-common \
          llvm \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          libxml2-dev \
          libxmlsec1-dev \
          libffi-dev \
          liblzma-dev \
          libpq-dev \
          ninja-build \
          pkg-config \
          libgtk-3-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libxcb-xfixes0-dev \
          libxkbcommon-dev \
          libqt5webkit5 \
          golang \
          unzip \
          direnv \
          neofetch \
          ranger \
          xsel 


- link:
    ~/.config/bat: bat
