- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Disable DNS NetworkManager processing
      command: |
        sudo cp etc/90-no-dns.conf /etc/NetworkManager/conf.d
        sudo rm /etc/resolv.conf
        sudo cp etc/resolv.conf /etc/resolv.conf
         
        if [[ -f "mglu/resolv.conf" ]]; then
          cat mglu/resolv.conf | sudo tee -a /etc/resolv.conf
        fi
        sudo systemctl reload NetworkManager
