- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Installing docker dependencies
      command: |
        sudo apt-get update
        sudo apt-get install -y \
          lsb-release \
          ca-certificates \
          apt-transport-https \
          software-properties-common \
          wget \
          curl
    - description: Installing docker
      command: |
        if [ ! -f  '/usr/share/keyrings/docker-archive-keyring.gpg' ]; then
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
          sudo apt-get update
        fi
        sudo apt-get install -y \
          docker-ce \
          docker-ce-cli
        sudo usermod -aG docker $USER
    - description: Installing docker-compose
      command: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - description: Installing Lazydocker
      command: "[ `uname` = 'Linux' ] && curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | zsh"
      stderr: true
      stdout: true
