- create:
    - ~/.docker/cli-plugins
- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing docker dependencies
    command: |
      if [ `uname` = 'Linux' ]; then
        case $(lsb_release -is) in 
          Ubuntu)
            sudo apt-get update
            sudo apt-get install -y \
            lsb-release \
            ca-certificates \
            apt-transport-https \
            software-properties-common \
            wget \
            curl \
            gnupg
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm libxcrypt-compat 
          ;;
        esac
      fi
  - description: Installing docker
    command: |
      if [ `uname` = 'Darwin' ]; then
        brew install --cask docker
      elif [ `uname` = 'Linux' ]; then
        case $(lsb_release -is) in 
          Ubuntu)
            if [ ! -f  '/etc/apt/keyrings/docker.gpg' ]; then
              # Add Docker's official GPG key:
              sudo install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              sudo chmod a+r /etc/apt/keyrings/docker.gpg
              # Add the repository to Apt sources:
              echo \
                "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
            fi
            sudo apt-get install -y \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin 

            sudo groupadd docker
            sudo usermod -aG docker $USER
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm docker
            sudo systemctl enable --now docker
            sudo groupadd -f docker
            sudo usermod -aG docker $USER
            newgrp docker
            sudo chmod 666 /var/run/docker.sock
          ;;
        esac
      fi
  - description: Installing docker-compose
    command: |
      if [ `uname` = 'Darwin' ]; then
        brew install docker-compose 
      elif [ `uname` = 'Linux' ]; then
        case $(lsb_release -is) in 
          Ubuntu)
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            version="v2.24.0"
            curl -SL https://github.com/docker/compose/releases/download/${version}/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            # sudo chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm docker-compose
          ;;
        esac
      fi
      ~/.docker/cli-plugins/docker-compose version
      docker compose version

  - description: Installing Lazydocker
    command: |
      if [ `uname` = 'Darwin' ]; then
        brew install jesseduffield/lazydocker/lazydocker 
      elif [ `uname` = 'Linux' ]; then
        curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
      fi
