- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Install first packages
      command: |
        sudo pacman -Syu --noconfirm bitwarden
        yay -Syu --noconfirm --nodiffmenu \
          authy \
          bitw-git

    - description: Install packages
      command: |
        sudo pacman -Syu --noconfirm \
          zsh \
          exa \
          bat \
          xsel \
          xclip \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs \
          dbeaver \
          qutebrowser \
          flameshot \
          maim \
          peek \
          seahorse \
          picom

    - description: Install bluetooth
      command: |
        sudo pacman -S --noconfirm --needed \
          bluez \
          bluez-utils \
          blueman \
          pipewire-pulse
        sudo systemctl enable bluetooth

    - description: Install yay packages
      command: |
        yay -Syu --noconfirm \
          brave-nightly-bin \
          ferdium \
          notion-app \
          postman-bin \
          insomnia-bin \
          termius-beta \
          rofi-greenclip

    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin

    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - description: Disable DNS NetworkManager processing
      command: |
        echo "[main]\\ndns=none\\nrc-manager=unmanaged" | sudo tee /etc/NetworkManager/conf.d/no-dns.conf      
        sudo rm /etc/resolv.conf
        sudo cp etc/resolv.conf /etc/resolv.conf
         
        if [[ -f "mglu/resolv.conf" ]]; then
          cat mglu/resolv.conf | sudo tee -a /etc/resolv.conf
        fi
        sudo systemctl restart NetworkManager.service
        #echo "nameserver 8.8.8.8\\nnameserver 8.8.4.4\\nnameserver 1.1.1.1\\nnameserver 1.0.0.1\\nnameserver 10.0.0.150\\nnameserver 10.0.0.151" | sudo tee /etc/resolv.conf

- link:
    ~/.config/i3: i3
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/gtk-3.0: gtk-3.0
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
    ~/.config/greenclip.toml: greenclip/greenclip.toml
    ~/.config/wallpapers: wallpapers
