- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"
    - description: Install first packages
      command: | 
        sudo pacman -Syu --noconfirm bitwarden
        yay -Syu --nocleanmenu --noconfirm --nodiffmenu \
          authy \
          bitw-git
    - description: Install packages
      command: |
        sudo pacman -Syu  --noconfirm \
          exa \
          bat \
          xsel \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs \
          dbeaver
          # whatsapp-for-linux \
          # telegram-desktop \
          # vlc \
          # slack \
          # firetruck \
    - description: Install bluetooth
      command: |
        sudo pacman -Syu --needed bluez bluez-utils blueman
        sudo systemctl enable --now bluetooth
    - description: Install yay packages
      command: |
        yay -Syu --nocleanmenu --noconfirm --nodiffmenu \
          brave-nightly-bin \
          spotify \
          ferdium \
          notion-app \
          postman-bin \
          insomnia \
          termius-beta
    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin
    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  
- link:
    ~/.config/i3: i3/endeavouros
    ~/.config/dunst: dunst/endeavouros
    ~/.config/rofi: rofi/endeavouros
    ~/.config/gtk-3.0: gtk-3.0/endeavouros
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/endeavouros_picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat

      #client_id:
      #user.251fa982-74fd-4d64-b905-ad4a017cda75

      #client_secret:
      #hZs2p2F3o3zLlXEdN8DhyVPiVPeG25

      #scope:
      #api

      #grant_type:
      #client_credentials
