- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Configure keyboard
      command: |
        sudo cp xorg/00-keyboard.conf /etc/X11/xorg.conf.d/

    - description: Install first packages
      command: |
        sudo pacman -Syu --noconfirm bitwarden
        yay -Syu --noconfirm --nodiffmenu \
          authy \
          bitw-git

    - description: Install packages
      command: |
        sudo pacman -Syu --noconfirm \
          zsh \
          exa \
          bat \
          xsel \
          xclip \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs \
          dbeaver \
          flameshot \
          maim \
          peek \
          libsecret \
          seahorse \
          picom \
          telegram-desktop

    - description: Install bluetooth
      command: |
        sudo pacman -S --noconfirm --needed \
          bluez \
          bluez-utils \
          blueman 
        sudo systemctl enable --now bluetooth

    - description: Install yay packages
      command: |
        yay -Syu --noconfirm \
          slack-desktop \
          ferdium \
          notion-app \
          postman-bin \
          insomnia-bin \
          termius-beta \
          rofi-greenclip \
          whatsapp-for-linux \
          discord-canary

    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin

    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - description: Disable DNS NetworkManager processing
      command: |
        sudo cp etc/90-no-dns.conf /etc/NetworkManager/conf.d
        sudo rm /etc/resolv.conf
        sudo cp etc/resolv.conf /etc/resolv.conf
         
        if [[ -f "mglu/resolv.conf" ]]; then
          cat mglu/resolv.conf | sudo tee -a /etc/resolv.conf
        fi
        sudo systemctl reload NetworkManager
- link:
    ~/.config/i3: i3
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/gtk-3.0: gtk-3.0
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
    ~/.config/greenclip.toml: greenclip/greenclip.toml
    ~/.config/wallpapers: wallpapers
