- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"
    - description: Install first packages
      command: | 
        sudo pacman -Syu --noconfirm bitwarden
        yay -S authy
    - description: Install packages
      command: |
        sudo pacman -Syu  --noconfirm \
          exa \
          bat \
          xsel \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs
          notion \
          dbeaver-ce \
          postman \
          insomnia \
          whatsapp-for-linux \
          telegram-desktop \
          vlc \
          slack \
          termius-beta \
          firetruck
    - description: Install bluetooth
      command: |
        sudo pacman -Syu --needed bluez bluez-utils blueman
        sudo systemctl enable --now bluetooth
    - description: Install globalprotect
      command: |
        sudo pacman -S --noconfirm globalprotect-openconnect
    - description: Install yay packages
      command: |
        yay -S \
          brave-nightly-bin \
          spotify \
          ferdium 
    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin

- link:
    ~/.config/i3: i3/endeavouros
    ~/.config/dunst: dunst/endeavouros
    ~/.config/rofi: rofi/endeavouros
    ~/.config/gtk-3.0: gtk-3.0/endeavouros
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/endeavouros_picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
