- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Install first packages
      command: |
        sudo pacman -Syu --noconfirm bitwarden
        yay -Syu --noconfirm --nodiffmenu \
          authy \
          bitw-git

    - description: Install packages
      command: |
        sudo pacman -Syu --noconfirm \
          zsh \
          exa \
          bat \
          xsel \
          xclip \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs \
          dbeaver \
          qutebrowser \
          flameshot \
          maim \
          peek \
          seahorse

    - description: Install bluetooth
      command: |
        sudo pacman -S --noconfirm --needed \
          bluez \
          bluez-utils \
          blueman \
          pipewire-pulse
        sudo systemctl enable bluetooth

    - description: Install yay packages
      command: |
        yay -Syu --noconfirm \
          brave-nightly-bin \
          ferdium \
          notion-app \
          postman-bin \
          insomnia-bin \
          termius-beta \
          rofi-greenclip

    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin

    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - description: Install Spotify/Spicetify
      command: |
        yay -Syu  --noconfirm \
          spotify \
          spotifyd \
          spotify-tui

        systemctl --user enable spotifyd.service
        #secret-tool store --label='name you choose' application rust-keyring service spotifyd username <your-username>

- link:
    ~/.config/i3: i3/endeavouros
    ~/.config/dunst: dunst/endeavouros
    ~/.config/rofi: rofi/endeavouros
    ~/.config/gtk-3.0: gtk-3.0/endeavouros
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/endeavouros_picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
    ~/.config/greenclip.toml: i3/endeavouros/greenclip.toml
    ~/.config/spotify-tui/config.yml: spotify-tui/config.yml
    ~/.config/spotifyd/spotifyd.conf: spotifyd/spotifyd.conf
