- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Configure keyboard
      command: |
        sudo cp xorg/00-keyboard.conf /etc/X11/xorg.conf.d/

- link:
    ~/.config/i3: i3
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/gtk-3.0: gtk-3.0
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
    ~/.config/greenclip.toml: greenclip/greenclip.toml
    ~/.config/wallpapers: wallpapers
