- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Install first packages
      command: | 
        sudo pacman -Syu --noconfirm bitwarden
        yay -Syu --noconfirm --nodiffmenu \
          authy \
          bitw-git

    - description: Install packages
      command: |
        sudo pacman -Syu --noconfirm \
          exa \
          bat \
          xsel \
          xclip \
          xterm \
          ranger \
          neofetch \
          git-delta \
          postgresql-libs \
          dbeaver \
          qutebrowser \
          flameshot \
          maim \
          peek

    - description: Install bluetooth
      command: |
        sudo pacman -Syu --noconfirm blueberry 
        sudo systemctl enable --now bluetooth

    - description: Install yay packages
      command: |
        yay -Syu --noconfirm \
          brave-nightly-bin \
          spotify \
          ferdium \
          notion-app \
          postman-bin \
          termius-beta \
          rofi-greenclip


    - description: Install ngrok
      command: |
        curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin

    - description: Install insomnia
      command: |
        yay -Syu insomnia-bin --noconfirm
        # [ -d $HOME/.local/src/insomnia ] && sudo rm -r $HOME/.local/src/insomnia
        # curl -sLo $HOME/.local/src/insomnia.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/insomnia.tar.gz
        # tar -xzf $HOME/.local/src/insomnia.tar.gz -C $HOME/.local/src
        # cd $HOME/.local/src/insomnia
        # makepkg -s
        # sudo pacman -U insomnia-*-x86_64.pkg.tar
  
    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  
- link:
    ~/.config/i3: i3/endeavouros
    ~/.config/dunst: dunst/endeavouros
    ~/.config/rofi: rofi/endeavouros
    ~/.config/gtk-3.0: gtk-3.0/endeavouros
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/endeavouros_picom.conf
    ~/.screenlayout: xrand
    ~/.config/bat: bat
    ~/.config/greenclip.toml: i3/endeavouros/greenclip.toml
