- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install bluetooth
      command: |
        sudo pacman -S --needed bluez bluez-utils blueman
        sudo systemctl enable --now bluetooth
    - description: Install globalprotect
      command: |
        sudo pacman -S --noconfirm globalprotect-openconnect
    - description: Install brave
      command: ["yay -S brave-nightly-bin"] 
    - description: Install spotify
      command: "sudo pacman -Syu --noconfirm spotify-launcher"
- link:
    ~/.config/i3: i3/endeavouros
    ~/.config/dunst: dunst/endeavouros
    ~/.config/rofi: rofi/endeavouros
    ~/.config/gtk-3.0: gtk-3.0/endeavouros
    ~/.config/xfce4/terminal: xfce4/terminal
    ~/.config/picom.conf: picom/endeavouros_picom.conf
    ~/.screenlayout: xrand
