- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install globalprotect
      command: |
        sudo pacman -S --noconfirm globalprotect-openconnect
        sudo pacman -S --needed bluez bluez-utils blueman
        sudo systemctl enable --now bluetooth
        yay -S brave-nightly-bin
- link:
    ~/.config/i3: endeavouros/i3
    ~/.config/dunst: endeavouros/dunst
    ~/.config/rofi: endeavouros/rofi
    ~/.config/gtk-3.0: endeavouros/gtk-3.0
    ~/.config/xfce4/terminal: endeavouros/xfce4/terminal
    ~/.config/picom.conf: endeavouros/picom.conf
