- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Installing packages
      command: |
        if [ ! -d $HOME/.fzf ]; then
          git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        fi
        cd $HOME/.fzf
        git pull
        ~/.fzf/install
      stdout: true
    - description: Installing optional dependencies
      command: |
        #Atualizar sources lists
        sudo apt-get -y update

        sudo apt-get install -y \
        ripgrep \
        universal-ctags \
        silversearcher-ag

        #Config fdfind
        #https://github.com/sharkdp/fd/releases/download/v8.6.0/fd_8.6.0_amd64.deb
        #sudo ln -fvs /usr/bin/fdfind /usr/bin/fd
- link:
    ~/.zshrc.d/011-fzf-ubuntu.zsh:
      if: "[ `uname` = Linux ]"
      path: zshrc.d/011-fzf-ubuntu.zsh
