- shell:
    - description: Validating .env
      command: scripts/git.sh
      stderr: true
      stdout: true
    - description: Install Lazygit
      command: |
        if [ `uname` = 'Linux' ]; then
          LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
          curl -Lo $HOME/.local/src/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
          sudo tar xf $HOME/.local/src/lazygit.tar.gz -C /usr/local/bin lazygit
        fi
      stderr: true
      stdout: true

- link:
    ~/.gitconfig: git/gitconfig
