- create:
    - ~/.local/src
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    # - description: Installing gvm dependencies
    #   command: |
    #     if [ `uname` = 'Linux' ]; then
    #       case $(lsb_release -is) in
    #         Ubuntu)
    #           sudo apt-get update
    #           sudo apt-get install -y \
    #           curl \
    #           git \
    #           mercurial \
    #           make \
    #           binutils \
    #           gcc \
    #           build-essential \
    #           bison
    #         ;;
    #         Arch | EndeavourOS)
    #           sudo pacman -Syu --noconfirm bison
    #         ;;
    #       esac
    #     elif [ `uname` = 'Darwin' ]; then
    #       # xcode-select --install
    #       brew update
    #       brew install mercurial
    #     fi

    - description: Remove previous gmv folder
      command: "[ ! -d ~/.gvm ] || sudo rm -rf ~/.gvm"

    - description: Install gvm
      command: |
        curl -sSL -o $HOME/.local/src/gvm-installer https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
        chmod +x $HOME/.local/src/gvm-installer 
        GVM_NO_UPDATE_PROFILE=yes \
          sh $HOME/.local/src/gvm-installer
        source $HOME/.gvm/scripts/gvm
        alias gvm="$HOME/.gvm/bin/gvm"
        gvm install go1.17 -B
        gvm use go1.17
        export GOROOT_BOOTSTRAP=$GOROOT
        gvm install go1.21.3
        gvm use go1.21.3 --default
        gvm list
        go version

      stdout: true

- link:
    ~/.zshrc.d/022-gvm.zsh: zshrc.d/022-gvm.zsh
