- create:
    - ~/.local/src
    - ~/.local/bin
    - ~/.local/share
    - ~/.kube
    - ~/.kube/hering
    - ~/Projects/Work/hering/
- shell:
    - command: '[ -d "$HOME/.ssh" ]  || mkdir $HOME/.ssh'
    - command: '[ -f "$HOME/.ssh/id_ed25519_hering" ]  || cp hering/ssh/id_ed25519_hering ~/.ssh/id_ed25519_hering'
    - command: '[ -f "$HOME/.ssh/id_ed25519_hering.pub" ]  || cp hering/ssh/id_ed25519_hering.pub ~/.ssh/id_ed25519_hering.pub'
    - [chmod 400 ~/.ssh/id_ed25519_hering]
    - [chmod 400 ~/.ssh/id_ed25519_hering.pub]
    # - command: '[ -d "$HOME/.kube" ]  || mkdir $HOME/.kube'
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install remmina
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm \
              remmina \
              freerdp
          ;;
        esac

    - description: Install forticlient
      command: |
        if [ `uname` = 'Linux' ]; then
          case $(lsb_release -is) in 
            Ubuntu)
              # Method 1
              sudo apt-get install -y openfortivpn
            ;;

            Arch | EndeavourOS)
              yay -S forticlientsslvpn --nocleanmenu --noconfirm --nodiffmenu
            ;; 
          esac
        elif [ `uname` = 'Darwin' ]; then
            brew install openfortivpn
            # Install hering/network/vpns/installers/macos/FortiClient_OnlineInstaller.dmg
        fi

    - [cp -r hering/kube/* ~/.kube/hering ] 
    - [sudo cp -r hering/network/vpn/configs/* /etc/openfortivpn/]
- link:
    ~/.gitconfig_hering: hering/git/gitconfig_hering
    ~/.zshrc.d/201-hering.zsh: hering/zsh/201-hering.zsh
