- shell:
    - description: Install i3-gaps
      command: |
        sudo add-apt-repository ppa:regolith-linux/release
        sudo apt update
        sudo apt install -y i3-gaps
      stdout: true
    - description: Install polybar
      command: |
        sudo apt install -y polybar

# - link:
#   ~/.config/i3: i3
#   ~/.config/rofi: rofi
