- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install i3-gaps
      command: |
        sudo add-apt-repository ppa:kgilmer/speed-ricer
        sudo apt update
        sudo apt install -y i3-gaps polybar picom

- link:
    ~/.config/i3: i3
    ~/.config/polybar: polybar
    ~/.config/picom: picom
