- create:
  - ~/.local/src
  - ~/.local/bin

- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"

  - description: Configure keyboard
    command: "[ -d /etc/X11/xorg.conf.d/ ] && sudo cp xorg/00-keyboard.conf /etc/X11/xorg.conf.d/"

  - description: Install i3
    command: |
      case $(lsb_release -is) in
        Ubuntu)
          sudo apt update
          sudo apt install -y \
            i3 \
            i3lock \
            i3status \
            i3blocks \
            suckless-tools \
            picom \
            rofi \
            nitrogen \
            feh \
            blueman \
            brightnessctl \
            terminator
        ;;
      esac
  - description: Install dunst
    command: |
      case $(lsb_release -is) in
        Ubuntu)
          sudo apt install -y \
            libdbus-1-dev \
            libx11-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libgtk-3-dev \
            libxdg-basedir-dev \
            libnotify-dev

          [ -d $HOME/.local/src/dunst ] || git clone https://github.com/dunst-project/dunst.git $HOME/.local/src/dunst
          cd $HOME/.local/src/dunst
          git pull
          make
          sudo make install
        ;;
      esac
      
- link:
    ~/.config/i3: i3
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/picom.conf: picom/picom.conf
    ~/.config/wallpapers: wallpapers
    
    ~/.config/greenclip.toml:
      if: '[`lsb_release -is` = EndeavourOS]'
      path: greenclip/greenclip.toml
    ~/.screenlayout:
      if: '[`lsb_release -is` = EndeavourOS]'
      path: xrand
    ~/.config/xfce4/terminal: 
      if: '[`lsb_release -is` = EndeavourOS]'
    ~/.config/gtk-3.0: 
      if: '[`lsb_release -is` = EndeavourOS]'
      path: gtk-3.0