- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install i3-gaps
      command: |
        sudo add-apt-repository ppa:kgilmer/speed-ricer
        sudo apt update
        sudo apt install -y \
        i3-gaps \
        polybar \
        picom \
        dunst \
        rofi \
        nitrogen \
        feh \
        blueman
    - [
        wget -qO- https://git.io/papirus-icon-theme-install | sh,
        Install papirus-icon-theme,
      ]
    - [ gsettings set org.gnome.desktop.interface icon-theme 'Papirus' ]

- link:
    ~/.config/i3: i3
    ~/.config/polybar: polybar
    ~/.config/picom: picom
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
