- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create source dir
      command: "[ -d $HOME/.local/src ] || mkdir -p $HOME/.local/src"
    - description: Install jetbrains-toolbox
      command: |
        version=1.27.3.14493
        if [[ `uname` == 'Linux' && ! -d $HOME/.local/src/jetbrains-toolbox-${version} ]]; then
          curl -L "https://download.jetbrains.com/toolbox/jetbrains-toolbox-$version.tar.gz" | tar -xz -C $HOME/.local/src/
        fi

        cd $HOME/.local/src/jetbrains-toolbox-${version}
        ./jetbrains-toolbox

- link:
    ~/.zshrc.d/015-jetbrains-toolbox.zsh: zshrc.d/015-jetbrains-toolbox.zsh
