- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create source dir 
      command: "[ -d $HOME/.local/src ] || mkdir -p $HOME/.local/src"
    - description: Install jetbrains-toolbox
      command: |
        version="1.27.3.14493"
        wget -v -P $HOME/.local/src https://download.jetbrains.com/toolbox/jetbrains-toolbox-${version}.tar.gz

        sudo tar xzf $HOME/.local/src/jetbrains-toolbox-${version}.tar.gz -C /opt/
        rm $HOME/.local/src/jetbrains-toolbox-${version}.tar.gz
        cd /opt/jetbrains-toolbox-${version}

        ./jetbrains-toolbox

- link:
    ~/.zshrc.d/015-jetbrains-toolbox.zsh: zshrc.d/015-jetbrains-toolbox.zsh
