- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Installing kind
      command: |
        if [ `uname` = 'Linux' ]; then
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.15.0/kind-linux-amd64
          chmod +x -v ./kind
          sudo mv -v ./kind /usr/local/bin/kind
        fi
    - description: Installing k9s
      command: |
        if [ `uname` = 'Linux' ]; then 
          curl -sS https://webinstall.dev/k9s | sh 
          if [ -x "$HOME/.local/bin/k9s" ]; then 
            sudo rm /usr/local/bin/k9s
            sudo mv "$HOME/.local/bin/k9s" /usr/local/bin
          fi
        fi
    - description: Installing minikube
      command: |
        if [[ `uname` == 'Linux' && ! -f /usr/local/bin/minikube  ]]; then
          curl -Lo $HOME/.local/src/minikube-linux-amd64 https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install $HOME/.local/src/minikube-linux-amd64  /usr/local/bin/minikube
        fi
    - description: Installing kubectx
      command: |
        [ -d /opt/kubectx ]             || sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
        [ -f /usr/local/bin/kubectx ]   || sudo ln -sf /opt/kubectx/kubectx /usr/local/bin/kubectx
        [ -f /usr/local/bin/kubens ]    || sudo ln -sf /opt/kubectx/kubens /usr/local/bin/kubens
    - [exec /bin/zsh]
