- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing kitty
    command: |
      if [ `uname` = 'Linux' ]; then 
        if [ ! -f ~/.local/bin/kitty ]; then
          curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=nightly launch=n
          sudo ln -s ~/.local/kitty.app/bin/kitty /usr/local/bin/
          cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
          cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
          sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
          sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
          #sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $HOME/.local/bin/kitty 1
          #sudo update-alternatives --set x-terminal-emulator $HOME/.local/bin/kitty
        fi
      elif [ `uname` = 'Darwin' ]; then 
        brew install --cask kitty
      fi
    stderr: true
    stdout: true

- link:
    ~/.config/kitty: kitty

