- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing kitty
    command: "scripts/kitty.install.sh"
    stderr: true
    stdout: true

- link:
    ~/.config/kitty: kitty

