- create:
    - ~/.local/src
    - ~/.local/bin
    - ~/.local/share
    - ~/.kube
    - ~/.cache/kube
- shell: 
    - description: Validating sudo credentials
      command: "sudo --validate"
    
    - description: Installing kubeswitch
      command: |
        if [ -f $HOME/.local/bin/switcher  ]; then
            sudo rm $HOME/.local/bin/switcher 
        fi
        
        OS=`uname`                      # Pick the right os: linux, darwin (intel only)
        VERSION=0.8.0                   # Pick the current version.
        curl -L -o $HOME/.local/bin/switcher https://github.com/danielfoehrKn/kubeswitch/releases/download/${VERSION}/switcher_${OS}_amd64
        chmod +x $HOME/.local/bin/switcher
- link:
     ~/.zshrc.d/017-switch-completions.zsh: zshrc.d/017-switch-completions.zsh
  #  ~/.kube/switch-config.yaml: kubeswitch/switch-config.yaml
