- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install bluetooth
      command: |
        case $(lsb_release -is) in
          Ubuntu)
            sudo apt install -y \
              blueman
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm --needed \
              bluez \
              bluez-utils \
              blueman 
            sudo systemctl enable --now bluetooth
          ;;
        esac
