- create:
    - ~/.temp-fonts
    - ~/.local/share/fonts
- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing apps
    command: | 
      TEMP_DIR_FONTS=$HOME/.temp-fonts
      LOCAL_SHARE_FONTS=$HOME/.local/share/fonts
      cp -rf fonts/* $LOCAL_SHARE_FONTS


      VERSION=v3.0.2

      FONTS=(
        "CascadiaCode"
        "FiraCode"
        "FiraMono"
        "Hack"
        "JetBrainsMono"
        "VictorMono"
        "IBMPlexMono"
        "SourceCodePro"
        "SpaceMono"
        "NerdFontsSymbolsOnly"
        "Uubntu"
        "UbuntuMono"
        "Inconsolata"
        "Iosevka"
        "IosevkaTerm"
        "FantasqueSansMono"
        "DroidSansMono"
        "Noto"
        "RobotoMono"
        "Terminus"
        "DejaVuSansMono"
      )


      if [ ! -d $LOCAL_SHARE_FONTS ]; then
        mkdir  $LOCAL_SHARE_FONTS
      fi


      if [ ! -d $TEMP_DIR_FONTS ]; then
        mkdir $TEMP_DIR_FONTS
      fi

      cd $TEMP_DIR_FONTS

      for i in "${FONTS[@]}"
        do
        ### sudo ./install.sh <Font-Name>
        wget "https://github.com/ryanoasis/nerd-fonts/releases/download/$VERSION/"$i".zip"
        unzip "$i".zip
      done

      cp -v *.ttf  $LOCAL_SHARE_FONTS
      fc-cache -fv
      sudo rm -r $TEMP_DIR_FONTS
  - description: Install icons symbols 
    command: |
      case $(lsb_release -is) in 
        Arch | EndeavourOS)
          sudo pacman -Syu --noconfirm \
            noto-fonts-emoji \
            ttf-joypixels
        ;;
      esac
