- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - [ wget -qO- https://git.io/papirus-icon-theme-install | sh, Install Papirus ]
  - [ gsettings set org.gnome.desktop.interface icon-theme 'Papirus' ]
