- shell:
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs" ]  || cp mglu/id_ed25519_luizalabs ~/.ssh/id_ed25519_luizalabs'
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs.pub" ]  || cp mglu/id_ed25519_luizalabs.pub ~/.ssh/id_ed25519_luizalabs.pub'
    - [ chmod 400 ~/.ssh/id_ed25519_luizalabs]
    - [ chmod 400 ~/.ssh/id_ed25519_luizalabs.pub]

- link:
    ~/.gitconfig_mglu: mglu/gitconfig_mglu 
