- shell:
    - command: '[ -d "$HOME/.ssh" ]  || mkdir $HOME/.ssh'
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs" ]  || cp mglu/ssh/id_ed25519_luizalabs ~/.ssh/id_ed25519_luizalabs'
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs.pub" ]  || cp mglu/ssh/id_ed25519_luizalabs.pub ~/.ssh/id_ed25519_luizalabs.pub'
    - [chmod 400 ~/.ssh/id_ed25519_luizalabs]
    - [chmod 400 ~/.ssh/id_ed25519_luizalabs.pub]
    - command: '[ -d "$HOME/.kube" ]  || mkdir $HOME/.kube'
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install remmina
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm \
              remmina \
              freerdp
          ;;
        esac

    - description: Install globalprotect
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
          # Method 1
          # sudo dpkg -i mglu/network/vpns/luizalabs/GlobalProtect_UI_deb-6.1.0.0-44.deb
          # sudo cp mglu/network/vpns/luizalabs/openssl.cnf /usr/lib/ssl/
          
          #Method 2
          sudo add-apt-repository -y ppa:yuezk/globalprotect-openconnect
          sudo apt-get update 
          sudo apt-get install -y globalprotect-openconnect
          if [ -x gnome-extensions ]; then
            git clone https://github.com/ubuntu/gnome-shell-extension-appindicator.git
            meson gnome-shell-extension-appindicator /tmp/g-s-appindicators-build
            ninja -C /tmp/g-s-appindicators-build install
            gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
          fi

          ;;
          Arch | EndeavourOS)
            sudo pacman -Syu --noconfirm globalprotect-openconnect
          ;;
        esac
    - description: Install forticlient
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
            # Method 1
            # sudo apt-get install openfortivpn
            # sudo cp mglu/network/vpns/hub/config /etc/openfortivpn
            
            #Method 2
            sudo apt-get install -y libgdk-pixbuf-xlib-2.0-0 libgdk-pixbuf2.0-0
            sudo dpkg -i mglu/network/vpns/hub/forticlient-sslvpn_4.4.2333-1_amd64.deb
          ;;

          Arch | EndeavourOS)
            yay -S forticlientsslvpn --nocleanmenu --noconfirm --nodiffmenu
          ;; 
        esac
    # - [ eval "$(ssh-agent -s)" ]
    # - [ ssh-add "$HOME/.ssh/id_ed25519_luizalabs"]
    # - [ sleep 5 ]
    - [mkdir -p $HOME/Projects/mglu/]
    - command: "[ -d ~/Projects/mglu/griphook ] || git clone git@gitlab.luizalabs.com:luizalabs/fintech/griphook.git      ~/Projects/mglu/griphook"
    - command: "[ -d ~/Projects/mglu/hagrid ]   || git clone git@gitlab.luizalabs.com:luizalabs/fintech/hagrid.git        ~/Projects/mglu/hagrid"
    - command: "[ -d ~/Projects/mglu/snape ]    || git clone git@gitlab.luizalabs.com:luizalabs/fintech/snape.git         ~/Projects/mglu/snape"
    - command: "[ -d ~/Projects/mglu/hogwarts ] || git clone git@gitlab.luizalabs.com:luizalabs/fintech/hogwarts.git      ~/Projects/mglu/hogwarts/"

    - command: "[ -d ~/Projects/mglu/cicd_griphook ]  || git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/griphook.git   ~/Projects/mglu/cicd_griphook ]"
    - command: "[ -d ~/Projects/mglu/cicd_hagrid ]    || git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/hagrid.git   ~/Projects/mglu/cicd_hagrid ]"
    - command: "[ -d ~/Projects/mglu/cicd_snape ]     || git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/snape.git   ~/Projects/mglu/cicd_snape ]"
    - command: "[ -d ~/Projects/mglu/cicd_hogwarts ]  || git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/hogwarts.git   ~/Projects/mglu/cicd_hogwarts ]"
    # - description: Config hosts
    #   command: 'cat mglu/network/hosts.conf | sudo tee -a /etc/hosts'
    - description: Config DNS NetworkManager
      command: |
        if [[ -f "mglu/network/resolv.conf" ]]; then
          cat mglu/network/resolv.conf | sudo tee -a /etc/resolv.conf
        fi
        sudo systemctl reload NetworkManager
- link:
    ~/.gitconfig_mglu: mglu/git/gitconfig_mglu
    ~/.kube/mglu/eks-development.yaml: mglu/kube/eks-development.yaml
    ~/.kube/mglu/eks-hml-pagamentos.yaml: mglu/kube/eks-hml-pagamentos.yaml
    ~/.kube/mglu/eks-prd-pagamentos.yaml: mglu/kube/eks-prd-pagamentos.yaml
    ~/.kube/mglu/eks-production.yaml: mglu/kube/eks-production.yaml
    ~/.kube/switch-config.yaml: mglu/kubeswitch/switch-config.yaml
    ~/.zshrc.d/200-mglu.zsh: mglu/zsh/200-mglu.zsh
    ~/.config/gcloud/configurations/config_magalu-dict: mglu/gcloud/configurations/config_magalu-dict
