- shell:
    - command: '[ -d "$HOME/.ssh" ]  || mkdir $HOME/.ssh'
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs" ]  || cp mglu/id_ed25519_luizalabs ~/.ssh/id_ed25519_luizalabs'
    - command: '[ -f "$HOME/.ssh/id_ed25519_luizalabs.pub" ]  || cp mglu/id_ed25519_luizalabs.pub ~/.ssh/id_ed25519_luizalabs.pub'
    - [chmod 400 ~/.ssh/id_ed25519_luizalabs]
    - [chmod 400 ~/.ssh/id_ed25519_luizalabs.pub]
    - command: '[ -d "$HOME/.kube" ]  || mkdir $HOME/.kube'
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install remmina
      command: |
        sudo pacman -Syu --noconfirm \
          remmina \
          freerdp\
    - description: Install globalprotect
      command: |
        sudo pacman -Syu --noconfirm globalprotect-openconnect
    - description: Install forticlient
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
            wget -O - https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY | sudo apt-key add -
            echo 'deb [arch=amd64] https://repo.fortinet.com/repo/6.4/ubuntu/ /bionic multiverse' |  sudo tee /etc/apt/sources.list.d/forticlient.list 

            sudo apt-get update
            sudo apt install -y forticlient
          ;;

          Arch | EndeavourOS)
            yay -S forticlientsslvpn --nocleanmenu --noconfirm --nodiffmenu
          ;; 
        esac
    # - [ eval "$(ssh-agent -s)" ]
    # - [ ssh-add "$HOME/.ssh/id_ed25519_luizalabs"]
    # - [ sleep 5 ]
    - [ mkdir -p $HOME/Projects/mglu/]
    - [ git clone git@gitlab.luizalabs.com:luizalabs/fintech/griphook.git   ~/Projects/mglu/griphook ] 
    - [ git clone git@gitlab.luizalabs.com:luizalabs/fintech/hagrid.git     ~/Projects/mglu/hagrid ] 
    - [ git clone git@gitlab.luizalabs.com:luizalabs/fintech/snape.git      ~/Projects/mglu/snape ] 
    - [ git clone git@gitlab.luizalabs.com:luizalabs/fintech/hogwarts.git   ~/Projects/mglu/hogwarts ]

    - [ git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/hagrid.git   ~/Projects/mglu/cicd_hagrid ] 
    - [ git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/griphook.git ~/Projects/mglu/cicd_griphook ] 
    - [ git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/snape.git    ~/Projects/mglu/cicd_snape ] 
    - [ git clone git@gitlab.luizalabs.com:cicd/fintech/magalu-pagamentos/squad-pix/hogwarts.git ~/Projects/mglu/cicd_hogwarts ] 
- link:
    ~/.gitconfig_mglu: mglu/gitconfig_mglu
    ~/.kube/mglu/eks-development.yaml: mglu/kube/eks-development.yaml
    ~/.kube/mglu/eks-hml-pagamentos.yaml: mglu/kube/eks-hml-pagamentos.yaml
    ~/.kube/mglu/eks-prd-pagamentos.yaml: mglu/kube/eks-prd-pagamentos.yaml
    ~/.kube/mglu/eks-production.yaml: mglu/kube/eks-production.yaml
    ~/.kube/switch-config.yaml: mglu/kubeswitch/switch-config.yaml
    ~/.zshrc.d/200-mglu.zsh: mglu/200-mglu.zsh
