- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    
    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Install ngrok
      command: |
        if [ `uname` = 'Darwin' ]; then 
          brew install ngrok/ngrok/ngrok
        elif [ `uname` = 'Linux' ]; then
          curl -sLo $HOME/.local/src/ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar xvzf $HOME/.local/src/ngrok.tgz  -C /usr/local/bin
        fi
        