- shell:
  - description: Installing packages
    command: "./scripts/nvim.install.sh"
    stdout: true
    stderr: true
  - description: Install packer.nvim
    command: '[ ! -f $HOME/.local/share/nvim/site/pack/packer ] || git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim'

- link:
    ~/.config/nvim: nvim
