# VIM-PLUG
- shell:   
  - description: Installing vim-plug
    command: "[ -f ~/.local/share/nvim ] || curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  - description: Installing vim plugins
    command: "vim +PlugInstall +qa"

- link:
    ~/.config/nvim: nvim      