- shell:
  - description: Installing packages
    command: |
      sudo add-apt-repository ppa:neovim-ppa/unstable -y \
        && sudo apt-get update -y \
        && sudo apt-get install -y neovim
    stdout: true
    stderr: true
  - description: Install packer.nvim
    command: '[ ! -f $HOME/.local/share/nvim/site/pack/packer ] || git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim'

- link:
    ~/.config/nvim: nvim
