- shell:
  - description: Clone nvm 
    command: 'git clone https://github.com/nvm-sh/nvm.git ~/.nvm'
    stderr: true
  - description: Install node 
    command: "./scripts/npm.install.sh"
    stderr: true
    stdout: true
