- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Create ~/.local/bin
    command: "[ -x ~/.local/bin ] || mkdir -p ~/.local/bin"     
  - description: Installing packages
    command: "./scripts/packages.sh"
    stdout: true
    stderr: true
- shell: 
  - description: Customize fonts
    command: "fc-cache -vf ~/.fonts/"
