- shell:
    - command: '[ -f "$HOME/.ssh/id_ed25519" ]  || cp personal/ssh/id_ed25519 ~/.ssh/id_ed25519'
    - command: '[ -f "$HOME/.ssh/id_ed25519.pub" ]  || cp personal/ssh/id_ed25519.pub ~/.ssh/id_ed25519.pub'
    - [ chmod 400 ~/.ssh/id_ed25519]
    - [ chmod 400 ~/.ssh/id_ed25519.pub]

- link:
    ~/.gitconfig_local:                   personal/gitconfig_local
    ~/.wakatime.cfg:                      personal/wakatime.cfg
    ~/.ssh/known_hosts:                   personal/ssh/known_hosts
    ~/.config/ngrok/ngrok.yml:            personal/ngrok.yml
    ~/.config/spotify-tui/client.yml:     personal/spotify-client.yml
