- shell:
    - description: Install phpenv
      command: '[ -d "$HOME/.phpenv" ] || git clone git@github.com:phpenv/phpenv.git $HOME/.phpenv'
    - "[ -d $HOME/.phpenv/plugins/php-build ] || git clone https://github.com/php-build/php-build.git $HOME/.phpenv/plugins/php-build"
    - "[ -d $HOME/.phpenv/versions/8.2.9 ] || $HOME/.phpenv/bin/phpenv install 8.2.9"
    - "[ -d $HOME/.phpenv/versions/8.2.9 ] && $HOME/.phpenv/bin/phpenv global 8.2.9"
    - "[ -d $HOME/.phpenv/versions/7.4.8 ] || $HOME/.phpenv/bin/phpenv install 7.4.8"
    - "[ -d $HOME/.phpenv/versions/5.6.20 ] || $HOME/.phpenv/bin/phpenv install 5.6.20"
    # - [$HOME/.pyenv/shims/pip install neovim, "Install neovim"]

- link:
    ~/.zshrc.d/021-phpenv.zsh: zshrc.d/021-phpenv.zsh
