- create:
    - ~/.local/src
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Remove previous phpenv folder
      command: "[ ! -d ~/.phpenv ] || sudo rm -rf ~/.phpenv"

    - description: Install PHP prerequisites
      command: |
        if [ `uname` = 'Darwin' ]; then
          brew install autoconf \
            automake \
            bison \
            freetype \
            gd \
            gettext \
            icu4c \
            krb5 \
            libedit \
            libiconv \
            libjpeg \
            libpng \
            libxml2 \
            libzip \
            pkg-config \
            re2c \
            zlib \
            gmp \
            libsodium \
            imagemagick \
            apr \
            apr-util \
            argon2 \
            aspell \
            curl \
            freetds \
            libpq \
            libzip \
            oniguruma \
            pcre2 \
            sqlite \
            tidy-html5 \
            unixodbc \
            bzip2 \
            libffi \
            libxml2 \
            libxslt \
            mcrypt
        fi
        if [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              sudo apt-get install -y \
               autoconf \
               re2c \
               bison \
               libsqlite3-dev \
               libpq-dev \
               libonig-dev \
               libfcgi-dev \
               libfcgi0ldbl \
               libjpeg-dev \
               libpng-dev \
               libssl-dev \
               libxml2-dev \
               libcurl4-openssl-dev \
               libxpm-dev \
               libgd-dev \
               libmysqlclient-dev \
               libfreetype6-dev \
               libxslt1-dev \
               libpspell-dev \
               libzip-dev \
               libgccjit-10-dev \
               libtidy-dev
          esac
        fi

    - description: Remove previous phpenv folder
      command: "[ ! -d ~/.phpenv ] || rm -rf ~/.phpenv"

    - [
        git clone https://github.com/phpenv/phpenv.git           $HOME/.phpenv,
        "Install php-build",
      ]
    - [
        git clone https://github.com/php-build/php-build.git     $HOME/.phpenv/plugins/php-build,
        "Install php-build",
      ]
    - [
        git clone https://github.com/ngyuki/phpenv-composer.git  $HOME/.phpenv/plugins/phpenv-composer,
        "Install phpenv-composer",
      ]
    - [
        git clone https://github.com/madumlao/phpenv-aliases.git $HOME/.phpenv/plugins/phpenv-aliases,
        "Install phpenv-aliases",
      ]

    # - description: Install php 5.6.40
    #   command: |
    #     alias phpenv="$HOME/.phpenv/bin/phpenv"
    #     if [ `uname` = 'Darwin' ]; then
    #       PHP_BUILD_ZTS_ENABLE=off \
    #         PHP_BUILD_XDEBUG_ENABLE=on \
    #         PHP_BUILD_CONFIGURE_OPTS="\\
    #           --with-bz2=$(brew --prefix bzip2) \\
    #           --with-curl=$(brew --prefix curl) \\
    #           --with-iconv=$(brew --prefix libiconv) \\
    #           --with-openssl=$(brew --prefix openssl) \\
    #           --with-zlib=$(brew --prefix zlib)" \
    #       phpenv install 5.6.40
    #     fi
    #     if [ `uname` = 'Linux' ]; then
    #       case $(lsb_release -is) in
    #         Ubuntu)
    #           PHP_BUILD_XDEBUG_ENABLE=off \
    #           PHP_BUILD_ZTS_ENABLE=off \
    #           PHP_BUILD_CONFIGURE_OPTS="" \
    #           phpenv install 5.6.40
    #       esac
    #     fi
    #     phpenv rehash

    # - description: Install php 7.4.30
    #   command: |
    #     alias phpenv="$HOME/.phpenv/bin/phpenv"
    #     if [ `uname` = 'Darwin' ]; then
    #       PKG_CONFIG_PATH=""
    #       for pkg in openssl icu4c libxml2; do
    #         PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(brew --prefix $pkg)/lib/pkgconfig"
    #       done
    #       export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}"
    #       export KERBEROS_LIBS="-lkrb5"
    #       export KERBEROS_CFLAGS=" "
    #       export EDIT_LIBS="-ledit"
    #       export EDIT_CFLAGS=" "
    #       PHP_BUILD_ZTS_ENABLE=off \
    #         PHP_BUILD_XDEBUG_ENABLE=on \
    #         PHP_BUILD_EXTRA_MAKE_ARGUMENTS=-j"$(getconf _NPROCESSORS_ONLN)" \
    #         PHP_BUILD_CONFIGURE_OPTS="\\
    #           --with-bz2=$(brew --prefix bzip2) \\
    #           --with-curl=$(brew --prefix curl) \\
    #           --with-iconv=$(brew --prefix libiconv) \\
    #           --with-openssl-dir=$(brew --prefix openssl) \\
    #           --with-zlib=$(brew --prefix zlib)" \
    #       phpenv install 7.4.30
    #     fi
    #     if [ `uname` = 'Linux' ]; then
    #       case $(lsb_release -is) in
    #         Ubuntu)
    #           PHP_BUILD_XDEBUG_ENABLE=off \
    #           PHP_BUILD_ZTS_ENABLE=off \
    #           PHP_BUILD_CONFIGURE_OPTS="" \
    #           phpenv install 7.4.30
    #       esac
    #     fi
    #     phpenv rehash

    - description: Install php 8.2.11 (global)
      command: |
        export PATH="$HOME/.phpenv/bin:$PATH"
        eval "$(phpenv init -)"
        phpenv versions

        if [ `uname` = 'Darwin' ]; then
          PHP_BUILD_XDEBUG_ENABLE=on \
          PHP_BUILD_ZTS_ENABLE=off \
          PHP_BUILD_EXTRA_MAKE_ARGUMENTS=-j"$(getconf _NPROCESSORS_ONLN)" \
          PHP_BUILD_CONFIGURE_OPTS="\\
            --with-bz2=$(brew --prefix bzip2) \\
            --with-curl=$(brew --prefix curl) \\
            --with-iconv=$(brew --prefix libiconv) \\
            --with-icu-dir=$(brew --prefix icu4c)" \
              phpenv install 8.2.11
        fi

        if [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              PHP_BUILD_XDEBUG_ENABLE=off \
              PHP_BUILD_ZTS_ENABLE=off \
              PHP_BUILD_CONFIGURE_OPTS="" \
              	phpenv  install 8.2.11
          esac
        fi

        phpenv rehash
        phpenv global 8.2.11
        composer --version

    - description: Install composer
      command: |
        export PATH="$HOME/.phpenv/bin:$PATH"

        if [ -x php ]; then
          composer --version
        fi

- link:
    ~/.zshrc.d/023-phpenv.zsh: zshrc.d/023-phpenv.zsh
  # https://gist.github.com/sergeyklay/a29224497375562ea26ea16b94a8cd37
