- shell:

  - description: Validating sudo credentials
    command: "sudo --validate"
  
  - description: Remove old files
    command: |
      # [ -d ~/.config/containers/ ] && rm -rf ~/.config/containers/
      # [ -d ~/.local/share/containers/ ] && rm -rf ~/.local/share/containers 
      # [ ls ~/.ssh/podman* >/dev/null 2>&1 ] && rm -rf ~/.ssh/podman*
    stdout: true 

  - description: Installing podman
    command: |
      if [ `uname` = 'Darwin' ]; then
        brew install podman
        podman --version
        podman machine init podman-rootless
        podman machine init podman-rootful --cpus 2 --memory 2048 --disk-size 20
        podman machine set --rootful podman-rootful
        podman system connection default podman-rootful-root
        podman machine start podman-rootful
        sudo podman info
      elif [ `uname` = 'Linux' ]; then
        case $(lsb_release -is) in 
          Ubuntu)
            # Ubuntu 20.10 and newer
            sudo apt-get -y install podman
          ;;
          Arch | EndeavourOS)
            sudo pacman -S podman
          ;;
        esac
      fi
    stdout: true
  - description: Installing podman-compose
    command: |
      $HOME/.pyenv/shims/pip3 install --upgrade pip
      $HOME/.pyenv/shims/pip3 install podman-compose
      [ -f $HOME/.pyenv/shims/podman-compose ] && $HOME/.pyenv/shims/podman-compose version

  # - description: Installing podman-desktop
  #   command: | 
  #     if [ `uname` = 'Darwin' ]; then
  #       brew install podman-desktop 
  #     elif [ `uname` = 'Linux' ]; then
  #       version=v1.4.0
  #       flatpak install --user $HOME/Downloads/podman-desktop-$version.flatpak 
  #     fi


- link:
    ~/.zshrc.d/024-podman.zsh: zshrc.d/024-podman.zsh
