- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install Postman-cli
      command: |
        #Postman-cli
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - description: Install Postman Desktop
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
            sudo snap install \
              postman
          ;;
        esac
