- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create source dir 
      command: "[ -d $HOME/.local/src ] || mkdir -p $HOME/.local/src"
    - description: Install Pycharm
      command: |
        SHORTCUTS_DIR="/usr/share/applications"
        version="231.7515.12"

        PYCHARM_SHORTCUT="[Desktop Entry]
        Version=${version}
        Type=Application
        Name=PyCharm Community Edition
        Icon=/opt/pycharm-community-${version}/bin/pycharm.svg
        Exec=\"/opt/pycharm-community-${version}/bin/pycharm.sh\" %f
        Comment=Python IDE for Professional Developers
        Categories=Development;IDE;
        Terminal=false
        StartupWMClass=jetbrains-pycharm-ce
        StartupNotify=true"


        wget -v -P $HOME/.local/src https://download.jetbrains.com/python/pycharm-community-${version}.tar.gz
        sudo tar xzf $HOME/.local/src/pycharm-community-${version}.tar.gz -C /opt/
        rm $HOME/.local/src/pycharm-community-${version}.tar.gz
        cd /opt/pycharm-community-${version}/bin

        #PYCHARM_ATALHO
        echo "${PYCHARM_SHORTCUT}"  | sudo tee "${SHORTCUTS_DIR}/jetbrains-pycharm.desktop"	

        sh pycharm.sh
