- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Removing older install and Installing Pyenv
      command: | 
        [ -d "$HOME/.pyenv" ] && sudo rm -fr $HOME/.pyenv
        curl https://pyenv.run | bash

    - "[ -d $HOME/.pyenv/versions/3.11.2 ] || $HOME/.pyenv/bin/pyenv install 3.11.2"
    - "[ -d $HOME/.pyenv/versions/3.11.2 ] && $HOME/.pyenv/bin/pyenv global 3.11.2"
    - "[ -d $HOME/.pyenv/versions/3.9.0 ] || $HOME/.pyenv/bin/pyenv install 3.9.0"
    - [$HOME/.pyenv/shims/pip install --upgrade pip, "Upgrade pip"]
    - [$HOME/.pyenv/shims/pip install neovim, "Install neovim"]

- link:
    ~/.zshrc.d/006-pyenv.zsh: zshrc.d/006-pyenv.zsh
