- shell:
  - description: Install pyenv
    command: '[ -d "$HOME/.pyenv" ] || curl https://pyenv.run | bash'
  - [ export PYENV_ROOT=$HOME/.pyenv ]
  - [ export PATH=$PYENV_ROOT/bin:$PATH ]
  - "[ -d $HOME/.pyenv/versions/3.11.2 ] || pyenv install 3.11.2"
  - "[ -d $HOME/.pyenv/versions/3.11.2 ] && pyenv global 3.11.2"
  - "[ -d $HOME/.pyenv/versions/3.9.0 ] || pyenv install 3.9.0"
  - [ pip install --upgrade pip, "Upgrade pip" ]
  - [ pip install awscli, "Install awscli" ]
  - [ pip install neovim, "Install neovim" ]
  # - [ exec $SHELL ]

- link:
    ~/.zshrc.d/006-pyenv.zsh: zshrc.d/006-pyenv.zsh
