- shell:
    - description: Install pyenv
      command: '[ -d "$HOME/.pyenv" ] || curl https://pyenv.run | bash'
    - [pyenv install 3.10.4]
    - [pyenv install 3.8.15]
    - [pyenv global 3.10.4]
    - [exec $SHELL]
