- shell:
    - description: Validating sudo credentials
      command: "sudo --validate" 
    - description: Create source dir 
      command: "[ -d $HOME/.local/src ] || mkdir -p $HOME/.local/src"
    - description: Install snaps
      command: |
        [ -d $HOME/.local/src/snapd ] || git clone https://aur.archlinux.org/snapd.git $HOME/.local/src/snapd
        cd $HOME/.local/src/snapd
        makepkg -si --noconfirm

        sudo systemctl enable --now snapd.socket

        if [ -f /var/lib/snapd/snap ]; then
          sudo ln -s /var/lib/snapd/snap /snap
        fi

        sudo systemctl start snapd

    - description: Install snaps
      command: |
        sudo snap install \
          authy \
          bitwarden \
          notion-snap \
          dbeaver-ce \
          postman \
          insomnia \
          whatsapp-for-linux \
          telegram-desktop \
          vlc \
          slack \
          spotify \
          termius-beta \
          firetruck
    - description: Install snaps --edges
      command: |
        sudo snap install --edge \
          ferdium \
          cacher
        sudo snap connect ferdium:camera
        sudo snap connect ferdium:audio-record
