- shell:
    - description: Install Spotify / Spotifyd / Spotify-tui
      command: |
        case $(lsb_release -is) in 
          Ubuntu)
            curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
            echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
            sudo apt-get update
            sudo apt-get install -y spotify-client
          ;;
          Arch | EndeavourOS)
            yay -Syu  --noconfirm \
              spotify
              # spotify \
              # spotifyd \
              # spotify-tui

            # systemctl --user enable spotifyd
          ;;
        esac

# - link:
#     ~/.config/spotify-tui/config.yml: spotify-tui/config.yml
#     ~/.config/spotifyd/spotifyd.conf: spotifyd/spotifyd.conf
#     ~/.config/systemd/user/spotifyd.service: spotifyd/spotifyd.service
