# Starship
- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing Starship
    command: "sh -c \"$(curl -sS https://starship.rs/install.sh)\""
    stderr: true
    stdout: true
- link:
    ~/.zshrc.d/100-starship.zsh: zshrc.d/100-starship.zsh
    ~/.config/starship.toml: starship/starship.toml
