- create:
    - ~/.local/src
    - ~/.local/bin
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Configure keyboard
      command: "[ -d /etc/X11/xorg.conf.d/ ] && sudo cp xorg/00-keyboard.conf /etc/X11/xorg.conf.d/"
    

    - description: Installing apps
      command: |
        sudo apt update -y
        sudo apt upgrade -y

        sudo apt install -y \
          sway \
          waybar

    # - description: Install Build prerequisites
    #   command: |
    #     if [ `uname` = 'Linux' ]; then 
    #       case $(lsb_release -is) in 
    #         Ubuntu)
    #           sudo apt install -y \
    #             meson
    #         ;;
    #
    #         # Arch | EndeavourOS)
    #         #   sudo pacman -Sy --noconfirm \
    #         #     base-devel \
    #         #     libevent \
    #         #     ncurses \
    #         #     make \
    #         #     bison \
    #         #     pkg-config
    #         # ;;
    #       esac
    #     fi

    # - description: Clean older versions
    #   command: |
    #     if [ -d $HOME/.local/src/wlroots ]; then 
    #       sudo rm -r $HOME/.local/src/wlroots 
    #     fi
    #     if [ -f /usr/local/bin/wlroots ]; then
    #       sudo rm /usr/local/bin/wlroots
    #     fi
    #     if [ -d $HOME/.local/src/sway ]; then 
    #       sudo rm -r $HOME/.local/src/sway 
    #     fi
    #     if [ -f /usr/local/bin/sway ]; then
    #       sudo rm /usr/local/bin/sway 
    #     fi
    # - description: Clone and build Wlroots
    #   command: |
    #     git clone https://gitlab.freedesktop.org/wlroots/wlroots.git $HOME/.local/src/wlroots
    #     cd $HOME/.local/src/wlroots
    #     meson build/
    #     ninja -C build/
    #     sudo ninja -C build/ install
    #   stdout: true

    # - description: Clone and build Sway
    #   command: |
    #     git clone https://github.com/swaywm/sway.git $HOME/.local/src/sway
    #     cd $HOME/.local/src/sway
    #     meson build/
    #     ninja -C build/
    #     sudo ninja -C build/ install
    #     sudo chmod a+s /usr/local/bin/sway
    #   stdout: true

- link:
    ~/.config/sway: sway
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/picom.conf: picom/picom.conf
    ~/.config/wallpapers: wallpapers
    ~/.config/greenclip.toml:
      if: "[`lsb_release -is` = EndeavourOS]"
      path: greenclip/greenclip.toml
    ~/.screenlayout:
      if: "[`lsb_release -is` = EndeavourOS]"
      path: monitors/xrand
    ~/.config/monitors.xml: monitors/monitors.xml
    ~/.config/gtk-3.0:
      if: "[`lsb_release -is` = EndeavourOS]"
      path: gtk-3.0
