- create:
    - ~/.local/src
    - ~/.local/bin
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install openssl
      command: |
        version=3.1.1
        curl -L "https://www.openssl.org/source/openssl-$version.tar.gz" | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/openssl-$version
        if [ `uname` = 'Darwin' ]; then
          ./Configure darwin64-x86_64-cc
        fi
        make test
        sudo make install
      stdout: true
    - description: Install libevent
      command: |
        version=2.1.12
        curl -L "https://github.com/libevent/libevent/releases/download/release-$version-stable/libevent-$version-stable.tar.gz" | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/libevent-$version-stable
        ./configure --enable-shared
        make 
        sudo make install
      stdout: true
    - description: Install ncurses
      command: |
        version=6.3
        curl -L https://invisible-island.net/datafiles/release/ncurses.tar.gz | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/ncurses-$version
        ./configure --with-shared --with-termlib --enable-pc-files
        make 
        sudo make install
      stdout: true
    - description: Install utf8proc
      command: |
        if [ `uname` = 'Darwin' ]; then
          version=2.8.0
          curl -L https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v$version.tar.gz | tar -xz -C $HOME/.local/src
          cd $HOME/.local/src/utf8proc-$version
          make
          sudo make install
        fi
      stdout: true

    - description: Build tmux
      command: |
        if [ `uname` = 'Darwin' ]; then
          brew install autoconf
          brew install automake
          brew install libtool
          brew install pkg-config
        elif [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              sudo apt install -y \
                libevent-dev \
                ncurses-dev \
                build-essential \
                bison \
                pkg-config
            ;;

            Arch | EndeavourOS)
              sudo pacman -Sy --noconfirm \
                base-devel \
                libevent \
                ncurses \
                make \
                bison \
                pkg-config
            ;;
          esac
        fi


        if [ !  -d $HOME/.local/src/tmux ]; then
          git clone https://github.com/tmux/tmux.git $HOME/.local/src/tmux
        fi 
        cd $HOME/.local/src/tmux
        git pull
        sh autogen.sh
        if [ `uname` = 'Darwin' ]; then
         ./configure --enable-utf8proc
        elif [ `uname` = 'Linux' ]; then 
          ./configure
        fi
        make 
        sudo make install

        if [ -d $HOME/.tmux ]; then
          sudo rm -r $HOME/.tmux
        fi
      stdout: true

    - description: "Clone TPM"
      command: |
        if [ ! -d $HOME/.tmux/plugins/tpm ]; then
          git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
        fi
        cd $HOME/.tmux/plugins/tpm
        git pull

    - description: Installing tmux-256color ( only macOS)
      command: |
        if [ `uname` = 'Darwin' ]; then
          curl -L https://invisible-island.net/datafiles/current/terminfo.src.gz | gunzip > $HOME/.local/src/terminfo.src
          sudo /usr/bin/tic -xe alacritty-direct,tmux-256color $HOME/.local/src/terminfo.src
          # /*/*/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
          
        fi

- link:
    ~/.tmux.conf:
      relink: true
      path: tmux/tmux.conf
    ~/.config/tmux:
      relink: true
      path: tmux/tmux
