- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - description: 'Clone TPM'
    command: 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'
    stdout: true
    stderr: true
- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.config/tmux/statusline.conf: tmux/statusline.conf
    ~/.config/tmux/utility.conf: tmux/utility.conf
