- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - [sudo apt-get install -y tmux]
    - [git submodule update --init --recursive, Installing submodules]
    - description: "Clone TPM"
      command: "[ -d $HOME/.tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm"

- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.config/tmux/tokyonight.conf: tmux/tokyonight.conf
    ~/.config/tmux/utility.conf: tmux/utility.conf
