- create:
    - ~/.local/src
    - ~/.local/bin
- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install openssl
      command: |
        version=3.1.1
        curl -L "https://www.openssl.org/source/openssl-$version.tar.gz" | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/openssl-$version
        if [ `uname` = 'Darwin' ]; then
          ./Configure darwin64-x86_64-cc
        elif [ `uname` = 'Linux' ]; then
          ./Configure
        fi
        make test
        sudo make install
      stdout: true
    - description: Install libevent
      command: |
        version=2.1.12
        curl -L "https://github.com/libevent/libevent/releases/download/release-$version-stable/libevent-$version-stable.tar.gz" | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/libevent-$version-stable
        ./configure --enable-shared
        make 
        sudo make install
      stdout: true
    - description: Install ncurses
      command: |
        version=6.3
        curl -L https://invisible-island.net/datafiles/release/ncurses.tar.gz | tar -xz -C $HOME/.local/src
        cd $HOME/.local/src/ncurses-$version
        ./configure --with-shared --with-termlib --enable-pc-files
        make 
        sudo make install
      stdout: true
    - description: Install utf8proc
      command: |
        if [ `uname` = 'Darwin' ]; then
          version=2.8.0
          curl -L https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v$version.tar.gz | tar -xz -C $HOME/.local/src
          cd $HOME/.local/src/utf8proc-$version
          make
          sudo make install
        fi
      stdout: true

    - description: Build prerequisites
      command: |
        if [ `uname` = 'Darwin' ]; then
          brew install autoconf
          brew install automake
          brew install libtool
          brew install pkg-config
        elif [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              sudo apt install -y \
                libevent-dev \
                ncurses-dev \
                build-essential \
                bison \
                pkg-config
            ;;

            Arch | EndeavourOS)
              sudo pacman -Sy --noconfirm \
                base-devel \
                libevent \
                ncurses \
                make \
                bison \
                pkg-config
            ;;
          esac
        fi
    - description: Clean older versions
      command: |
        if [ -d $HOME/.local/share/tmux/ ]; then 
          sudo rm -r $HOME/.local/share/tmux
        fi
        if [ -f /usr/local/bin/tmux ]; then
          sudo rm /usr/local/bin/tmux 
        fi
        if [ -d $HOME/.local/src/tmux ]; then 
          sudo rm -r $HOME/.local/src/tmux 
        fi
        if [ -d $HOME/.local/state/nvim ]; then 
          sudo rm -r $HOME/.local/state/nvim 
        fi
        if [ -d $HOME/.tmux ]; then
          sudo rm -r $HOME/.tmux
        fi

    - description: "Clone TMUX"
      command: |
        git clone https://github.com/tmux/tmux.git $HOME/.local/src/tmux
        cd $HOME/.local/src/tmux
        git pull
        git checkout 3.3a
        sh autogen.sh
        if [ `uname` = 'Darwin' ]; then
         ./configure --enable-utf8proc --prefix=$HOME/.local
        elif [ `uname` = 'Linux' ]; then 
          #./configure
          # Test config (https://github.com/tmux/tmux/issues/3218)
         ./configure --enable-debug --prefix=$HOME/.local
        fi
        make 
        make install

    - description: "Clone TPM"
      command: |
        if [ ! -d $HOME/.tmux/plugins/tpm ]; then
          git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
        fi
        cd $HOME/.tmux/plugins/tpm
        git pull

    - description: Installing tmux-256color (only macOS)
      command: |
        if [ `uname` = 'Darwin' ]; then
          #Method 1
          #curl -L https://invisible-island.net/datafiles/current/terminfo.src.gz | gunzip > $HOME/.local/src/terminfo.src
          #sudo /usr/bin/tic -xe tmux-256color $HOME/.local/src/terminfo.src
          #Method 2
          infocmp -x tmux-256color > $HOME/.local/src/tmux-256color.src
          sudo /usr/bin/tic -xe alacritty-direct,tmux-256color $HOME/.local/src/tmux-256color.src
          #Method 3
          infocmp -x tmux-256color > $HOME/.local/src/tmux-256color.src
          sudo tic -xe alacritty-direct,tmux-256color $HOME/.local/src/tmux-256color.src
        fi

- link:
    ~/.zshrc.d/021-tmux.zsh: zshrc.d/021-tmux.zsh
    ~/.tmux.conf:
      relink: true
      path: tmux/tmux.conf
    ~/.config/tmux:
      relink: true
      path: tmux/tmux
