- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Create source dir
      command: "[ -d $HOME/.local/src ] || mkdir -p $HOME/.local/src"
    - description: Build tmux
      command: |
        case $(lsb_release -is) in 

          Ubuntu)
            sudo apt install -y \
              libevent-dev \
              ncurses-dev \
              build-essential \
              bison \
              pkg-config
          ;;

          Arch | EndeavourOS)
            sudo pacman -Sy --noconfirm \
              base-devel \
              libevent \
              ncurses \
              make \
              bison \
              pkg-config
          ;;

        esac

        if [ !  -d $HOME/.local/src/tmux ]; then
          git clone https://github.com/tmux/tmux.git $HOME/.local/src/tmux
        fi 
        cd $HOME/.local/src/tmux
        git pull
        sh autogen.sh
        ./configure
        make && sudo make install

        if [ -d $HOME/.tmux ]; then
          sudo rm -r $HOME/.tmux
        fi

    # - description: Fallback tmux
    #   command: "[ -x /usr/local/bin/tmux ] || sudo apt-get install -y tmux"
    - description: "Clone TPM"
      command: |
        if [ ! -d $HOME/.tmux/plugins/tpm ]; then
          git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
        fi
        cd $HOME/.tmux/plugins/tpm
        git pull

- link:
    ~/.tmux.conf:
      relink: true
      path: tmux/tmux.conf
    ~/.config/tmux:
      relink: true
      path: tmux/tmux
