- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install snapd
      command: |
        if [ $(lsb_release -is) = 'Ubuntu' ]; then
            sudo apt install -y snapd
        fi

    - description: Install first snaps
      command: |
        sudo snap install \
          authy \
          bitwarden

    - description: Install snaps
      command: |
        if [ $(lsb_release -is) = 'Ubuntu' ]; then
          sudo snap install \
            notion-snap \
            insomnia \
            whatsapp-for-linux \
            telegram-desktop \
            termius-beta \
            firetruck
        fi
