- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Create ~/.local/src
      command: "[ -d ~/.local/src ] || mkdir -p ~/.local/src"

    - description: Configure keyboard
      command: |
        sudo cp xorg/00-keyboard.conf /etc/X11/xorg.conf.d/

    - description: Install first packages
      command: |
        sudo apt-get install -y \
          git \
          curl \
          make

    - description: Install i3
      command: |
        sudo apt update
        sudo apt install -y \
        i3 \
        i3lock \
        i3status \
        i3blocks \
        suckless-tools \
        picom \
        rofi \
        nitrogen \
        feh \
        blueman \
        brightnessctl
    - [
        wget -qO- https://git.io/papirus-icon-theme-install | sh,
        Install papirus-icon-theme,
      ]
    - [ gsettings set org.gnome.desktop.interface icon-theme 'Papirus' ]
    - description: Install dunst
      command: |
        sudo apt install -y \
        libdbus-1-dev \
        libx11-dev \
        libxinerama-dev \
        libxrandr-dev \
        libxss-dev \
        libglib2.0-dev \
        libpango1.0-dev \
        libgtk-3-dev \
        libxdg-basedir-dev \
        libnotify-dev

        git clone https://github.com/dunst-project/dunst.git $HOME/.local/src/dunst
        cd $HOME/.local/src/dunst
        make
        sudo make install
- link:
    ~/.config/i3: i3
    ~/.config/dunst: dunst
    ~/.config/rofi: rofi
    ~/.config/picom.conf: picom/picom.conf
    ~/.config/wallpapers: wallpapers
