- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"

    - description: Install flatpack
      command: |
        if [ $(lsb_release -is) = 'Ubuntu' ]; then           
          sudo apt-get install -y \
            gnome-software \
            gnome-software-plugin-flatpak \
            flatpak
          
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        fi

    - description: Install first snaps
      command: |
        sudo snap install \
          authy \
          bitwarden

    - description: Install snaps
      command: |
        if [ $(lsb_release -is) = 'Ubuntu' ]; then
          sudo snap install \
            insomnia \
            whatsapp-for-linux \
            telegram-desktop \
            termius-beta \
            redisinsight \
            firetruck
        fi
