- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Installing vscodium
    command: |
      wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
      | gpg --dearmor \
      | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg

      echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
      sudo apt update 
      sudo apt install -y codium

    stderr: true
    stdout: true

- link:
    # linux:
    "~/.config/VSCodium/User/settings.json":
      if: '[ `uname` = Linux ]'
      path: vscode/settings.json
    "~/.config/VSCodium/User/keybindings.json":
      if: '[ `uname` = Linux ]'
      path: vscode/keybindings.json
    "~/.config/VSCodium/User/snippets":
      if: '[ `uname` = Linux ]'
      path: vscode/snippets
    # macos:
    "~/Library/Application Support/VSCodium/User/settings.json":
      if: '[ `uname` = Darwin ]'
      path: vscode/settings.json
    "~/Library/Application Support/VSCodium/User/keybindings.json":
      if: '[ `uname` = Darwin ]'
      path: vscode/keybindings.json
    "~/Library/Application Support/VSCodium/User/snippets":
      if: '[ `uname` = Darwin ]'
      path: vscode/snippets

- shell:
  - description: Installing vscode extensions
    command: 'scripts/vscode.extensions.sh /usr/bin/codium'
    stdout: true
    stderr: true 
