- link:
    ~/Library/Application Support/Code/User/keybindings.json:
      if: '[ `uname` == "Darwin" ]'
      path: vscode/keybindings.json
    ~/Library/Application Support/Code/User/settings.json:
      if: '[ `uname` == "Darwin" ]'
      path: vscode/settings.json
