- create:
    - ~/Projects/zapay
- shell:
    - description: Clonning Projects
      command: |
        REPOS=(
          'api'
          'fleet-manager'
          'zpy-ticketlog'
          'slowking'
          'Unico'
          'zpy-payment-mercadopago-api'
          'zpy-payment-koin-api'
          'zents'
        )


        for i in "${REPOS[@]}"; do
          if [ ! -d $HOME/Projects/zapay/$i ]; then
            git clone git@github.com:zapay-pagamentos/$i $HOME/Projects/zapay/$i
          fi
        done

- link:
    ~/.aws/credentials: zapay/aws/credentials
    ~/.kube/zapay/zapay-production.yaml: zapay/kube/zapay-production.yaml
    ~/.kube/zapay/zapay-staging.yaml: zapay/kube/zapay-staging.yaml
