- shell:
    - description: Validating sudo credentials
      command: "sudo --validate"
    - description: Install zsh
      command: |
        if [ `uname` = 'Linux' ]; then 
          case $(lsb_release -is) in 
            Ubuntu)
              sudo apt-get install -y zsh
            ;;
            
            Arch | EndeavourOS)
              sudo pacman -S --noconfirm zsh
            ;;
          esac
        fi
    - description: Adding zsh to list of acceptable shells
      command: '[ -x $(which zsh) ] && sudo sh -c "echo $(which zsh) >> /etc/shells"'
    - [git submodule update --init --recursive, Installing submodules]
    - description: "Clone zgenom"
      command: "[ -d $HOME/zgenom ] || git clone https://github.com/jandamm/zgenom.git $HOME/zgenom"

- link:
    ~/.zgen-setup: zsh/zgenom-setup
    ~/.zsh_aliases: meta/zsh-quickstart-kit/zsh/.zsh_aliases
    ~/.zsh_functions: meta/zsh-quickstart-kit/zsh/.zsh_functions
    ~/.zshrc: meta/zsh-quickstart-kit/zsh/.zshrc
    ~/.zshrc.d/001-aliases.zsh: zshrc.d/001-aliases.zsh
    ~/.zshrc.d/002-nvm.zsh: zshrc.d/002-nvm.zsh
    ~/.p10k.zsh: powerlevel10k/p10k.zsh
    ~/.zshrc.d/013-local-path.zsh: zshrc.d/013-local-path.zsh
    ~/.zsh-quickstart-local-plugins: zshrc.d/zsh-quickstart-local-plugins
