- shell:
  - description: Validating sudo credentials
    command: "sudo --validate"
  - description: Adding zsh to list of acceptable shells
    command: "[[ \"$(ag $(which zsh) /etc/shells)\" ]] || sudo sh -c \"echo $(which zsh) >> /etc/shells\""
  - description: Making zsh the default shell
    command: "sudo chsh -s $(which zsh)"
  - [git submodule update --init --recursive, Installing submodules]
  - description: 'Clone zgenom'
    command: 'git clone https://github.com/jandamm/zgenom.git ~/zgenom'
    stdout: true
    stderr: true

- link:
    ~/.zgen-setup: zsh-quickstart-kit/zsh/.zgen-setup
    ~/.zsh_aliases: zsh-quickstart-kit/zsh/.zsh_aliases
    ~/.zsh_functions: zsh-quickstart-kit/zsh/.zsh_functions
    ~/.zshrc: zsh-quickstart-kit/zsh/.zshrc
    ~/.zshrc.d/001-aliases.zsh: zshrc.d/001-aliases.zsh
    ~/.zshrc.d/002-nvm.zsh: zshrc.d/002-nvm.zsh
    ~/.zshrc.d/003-brew-completations.zsh:
      if: '[ `uname` = Darwin ]'
      path: zshrc.d/003-brew-completations.zsh
    ~/.zshrc.d/004-java.zsh: zshrc.d/004-java.zsh
    ~/.zshrc.d/005-rust.zsh: zshrc.d/005-rust.zsh
    ~/.zshrc.d/006-pyenv.zsh:
      if: '[ $(which pyenv) ]'
      path: zshrc.d/006-pyenv.zsh
    ~/.zshrc.d/007-android.zsh: zshrc.d/007-android.zsh
    ~/.zshrc.d/008-flutter.zsh: zshrc.d/008-flutter.zsh
    ~/.zsh-quickstart-local-plugins:
