-- Plugins
require 'plugins.configs.nvimtree'
require 'plugins.configs.lualine'
require 'plugins.configs.telescope'
require 'plugins.configs.fzf'
require 'plugins.configs.bufferline'
require 'plugins.configs.nvim-treesitter'
require 'plugins.configs.nvim-treesitter-context'
require 'plugins.configs.indent-blankline'
