#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
ASDF_CONFIG="asdf/asdf.conf.yaml"
BREW_CONFIG="brew/brew.conf.yaml"
PACKAGES_CONFIG="packages/packages.conf.yaml"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive zsh-quickstart-kit

#dependencies
if [ $(uname -a | grep -ci Darwin) = 1 ]; then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -p dotbot-brewfile/brewfile.py -c "${BREW_CONFIG}" "${@}"
else
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -p dotbot-git/git.py -c "${PACKAGES_CONFIG}" "${@}"
fi

#asdf 
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -p dotbot-asdf/asdf.py -c "${ASDF_CONFIG}" "${@}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -p dotbot-git/git.py -c "${CONFIG}" "${@}"


