require("plugins.packer")
require("core.settings")
require("core.keymaps")
require("colorschemes.tokyonight")
-- Plugins
require("plugins.alpha-nvim")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.indent-blankline")
require("plugins.nvim-colorizer")
require("plugins.nvim-tmux-navigation")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.mason")
-- require("plugins.lspsaga")
-- require("plugins.lspconfig")
-- require("plugins.null-ls")
-- require("plugins.nvim-treesitter")
require("plugins.comment")
--require("plugins.gitsigns")
