k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_hering-opine-nps-prod_southamerica-east1_cluster-opine-nps-prod
  currentCluster: gke_hering-opine-nps-prod_southamerica-east1_cluster-opine-nps-prod
  clusters:
    gke_hering-opine-nps-prod_southamerica-east1_cluster-opine-nps-prod:
      namespace:
        active: opine-nps-dash
        lockFavorites: false
        favorites:
        - opine-nps-dash
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-fabio
